screening-fetch:
  days-ahead: 1
  cleanup:
    enabled: true
    days-to-keep: 0

providers:
  cinema-city:
    screenings:
      url-template: https://www.cinema-city.pl/pl/data-api-service/v1/quickbook/10103/cinema-events/in-group/katowice/with-film/%s/at-date/%s?attr=&lang=pl_PL
      enabled: true
