spring.application.name=movie-finder-server

spring.datasource.url=jdbc:sqlite:./db/cinema.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

server.port=8080

#spring.profiles.active=download-films
#spring.profiles.active=fetch-screenings
#spring.profiles.active=fetch-cinemas

# Scheduled import
import.scheduled.enabled=false
import.scheduled.cron=0 0 3 * * *

# Providers - cinemas
providers.cinema-city.cinemas.url=https://www.cinema-city.pl/pl/data-api-service/v1/quickbook/10103/cinemas/with-event/until/2027-01-31?attr=&lang=pl_PL
providers.cinema-city.cinemas.enabled=true
providers.multikino.cinemas.url=https://www.multikino.pl/api/microservice/showings/cinemas
providers.multikino.cinemas.enabled=true
providers.helios.cinemas.url=https://helios.pl/
providers.helios.cinemas.enabled=true
providers.helios.cinemas.fetch-details=true
providers.helios.cinemas.rate-limit-ms=1000

# Providers - films
providers.cinema-city.films.base-url=https://www.cinema-city.pl/pl/data-api-service/v1/10103/trailers/byCinemaId
providers.cinema-city.films.film-details-url=https://www.cinema-city.pl/pl/data-api-service/v1/10103/films/byDistributorCode
providers.cinema-city.films.cinema-ids=1088,1086,1092,1098,1089,1075,1099,1085,1065,1079,1090,1076,1064,1094,1084,1080,1081,1078,1062,1082,1083,1095,1077,1093,1091,1074,1061,1096,1069,1070,1068,1060,1067,1097,1087
providers.cinema-city.films.enabled=true
providers.multikino.films.url=https://www.multikino.pl/api/microservice/showings/films
providers.multikino.films.enabled=true
providers.multikino.films.limit=0
providers.helios.films.base-url=https://helios.pl
providers.helios.films.enabled=true
providers.helios.films.fetch-film-details=true
providers.helios.films.rate-limit-ms=1000
providers.helios.films.cinema-limit=0

# Providers - screenings
screening-fetch.days-ahead=21
screening-fetch.cleanup.enabled=false
screening-fetch.cleanup.days-to-keep=0
providers.cinema-city.screenings.url-template=https://www.cinema-city.pl/pl/data-api-service/v1/quickbook/10103/cinema-events/in-group/katowice/with-film/%s/at-date/%s?attr=&lang=pl_PL
providers.cinema-city.screenings.enabled=true
providers.multikino.screenings.base-url=https://www.multikino.pl/api/microservice/showings
providers.multikino.screenings.rate-limit-ms=500
providers.multikino.screenings.enabled=true
providers.multikino.screenings.cinema-limit=0
providers.helios.screenings.base-url=https://helios.pl
providers.helios.screenings.enabled=true
providers.helios.screenings.rate-limit-ms=1000
providers.helios.screenings.cinema-limit=0